# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireDemo
  pod 'Alamofire', '~> 3.0'
end
